In [47]:
import numpy as np

In [48]:
X = np.array([
    [1,0,1,1],
    [1,1,1,0],
    [1,1,0,1]
])

#First column is for bias

In [49]:
wHidden = np.array([
    [10,-20,20,-40],
    [20,-40,0,0]  
])

In [50]:
wOut = np.array([20,40,-40])

In [51]:
first_comp = np.dot(X,wHidden.T)

In [60]:
first_comp

array([[-10,  20],
       [ 10, -20],
       [-50, -20]])

In [52]:
def g(z):
    if z<=-10: return 0
    elif z>=10: return 1
    else: return 0.5
func = np.vectorize(g)  
res = func(first_comp)

In [53]:
res

array([[0, 1],
       [1, 0],
       [0, 0]])

In [56]:
#Add a column of ones for bias
res_bias = np.hstack((np.ones((3,1)),res))

In [57]:
res_bias

array([[1., 0., 1.],
       [1., 1., 0.],
       [1., 0., 0.]])

In [61]:
second_comp = np.dot(res_bias, wOut)

In [62]:
second_comp

array([-20.,  60.,  20.])

In [63]:
res_out = func(second_comp)

In [64]:
res_out

array([0, 1, 1])