In [1]:
import numpy as np

In [2]:
X = np.array([
    [1,0,1,1],
    [1,1,1,0],
    [1,1,0,1]
])

#First column is for bias

In [3]:
x1 = np.array([X[0]])
x2 = np.array([X[1]])
x3 = np.array([X[2]])
x1

array([[1, 0, 1, 1]])

In [4]:
miniBatch = np.concatenate((x1,x2), axis=0)

In [5]:
miniBatch

array([[1, 0, 1, 1],
       [1, 1, 1, 0]])

In [6]:
wHidden = np.array([
    [10,-20,20,-40],
    [20,-40,0,0]  
])

In [7]:
wOut = np.array([20,40,-40])

In [8]:
def g(z):
    if z<=-10: return 0
    elif z>=10: return 1
    else: return 0.5
func = np.vectorize(g) 
#Call: asd = func(xxxx)

#### Computation on all matrix

In [9]:
first_comp = np.dot(X,wHidden.T)

In [10]:
first_comp

array([[-10,  20],
       [ 10, -20],
       [-50, -20]])

In [11]:
res = func(first_comp)

In [12]:
res

array([[0, 1],
       [1, 0],
       [0, 0]])

In [13]:
#Add a column of ones for bias
res_bias = np.hstack((np.ones((3,1)),res))

In [14]:
res_bias

array([[1., 0., 1.],
       [1., 1., 0.],
       [1., 0., 0.]])

In [15]:
second_comp = np.dot(res_bias, wOut)

In [16]:
second_comp

array([-20.,  60.,  20.])

In [17]:
res_out = func(second_comp)

In [18]:
res_out

array([0, 1, 1])

### Computation on MiniBatch

In [19]:
batch_comp = np.dot(miniBatch, wHidden.T)

In [20]:
batch_comp

array([[-10,  20],
       [ 10, -20]])

In [21]:
res_batch = func(batch_comp)
res_batch

array([[0, 1],
       [1, 0]])

In [22]:
res_batch_bias = np.hstack((np.ones((2,1)),res_batch))

In [23]:
res_batch_bias

array([[1., 0., 1.],
       [1., 1., 0.]])

In [24]:
batch_comp2 = np.dot(res_batch_bias, wOut)

In [25]:
batch_comp2

array([-20.,  60.])

In [26]:
res_batch_out = func(batch_comp2)

In [27]:
res_batch_out

array([0, 1])