In [1]:
#https://iaml.it/blog/alle-prese-con-pytorch-parte-1

## PyTorch vs. NumPy

In [2]:
import numpy as np
import torch

In [3]:
x = np.zeros((2,3))
y = torch.zeros(2,3)

print(type(x), x.dtype)
print(type(y), y.dtype)

<class 'numpy.ndarray'> float64
<class 'torch.Tensor'> torch.float32


In [4]:
#Automatisches Casting numpy zu torch
z = x + y
print(type(z), z.dtype)

<class 'torch.Tensor'> torch.float64


In [5]:
print("Vor Umwandlung: ", z)
#Umwandlung zu numpy
#Die zwei Objekte teilen den Speicherraum!

#Umwandlung nach numpy
xx = z.numpy()
#Veräderung des Wertes von xx (!)
xx += 1.0

print("Nach Umwandlung:", z)

Vor Umwandlung:  tensor([[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]], dtype=torch.float64)
Nach Umwandlung: tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)


In [6]:
#Broadcasting für beide
torch.Tensor([3, 2]) * torch.Tensor([[0, 1], [4, 2]])

tensor([[  0.,   2.],
        [ 12.,   4.]])

In [7]:
torch.Tensor([3, 2]) + torch.Tensor([[0, 1], [4, 2]])

tensor([[ 3.,  3.],
        [ 7.,  4.]])

In [16]:
#Unterschied: Dimensionen axis vs dim
x = np.random.randint(1, 10,(2,3))
print(x)
x.mean(axis=0)

[[5 6 7]
 [3 1 6]]


array([4. , 3.5, 6.5])

In [17]:
y = torch.tensor(torch.randint(1,10,(2,3)))
print(y)
y.mean(dim=0)

tensor([[ 2.,  2.,  7.],
        [ 5.,  6.,  2.]])


tensor([ 3.5000,  4.0000,  4.5000])

In [19]:
#Automatische Berechnung des Gradienten

#Vor der Version 0.4.0 war eine Variable notwendig. Eine Variable in Torch ist eine 
#Art Wrapper um einen Tensor. Alle Änderungen an der Variablen werden in Torch innerhalb
#eines Graphen gespeichert

#Siehe gif

#In jedem Moment ist es möglich, den Gradienten von einer Funktion bzgl. eines Tensors
#Die notwendigen Informationen werden über den Graphen 
from torch.autograd import Variable
v = Variable(torch.ones(1, 2), requires_grad=True) #Das Flag sagt, dass der Gradient bzgl. v berechenbar ist

v_new = torch.ones((1,2), requires_grad=True) #Geht auch jetzt

print(v.data) #Unterliegender Tensor
print(v.grad) #Nicht initialisierter Gradient. Wird beim Backprop belegt
print(v.grad_fn) #So hält PyTorch den "Überblick" über den Graphe


tensor([[ 1.,  1.]])
None
None


In [20]:
v_fn = torch.sum(v ** 2)
print(v_fn.data)    # 2 [torch.FloatTensor of size 1]
print(v_fn.grad_fn) # <SumBackward0 object at 0x000001EA03790B70>

tensor(2.)


In [21]:
#Graphen sind in PyTorch dynamisch und das Ergebnis der Operationen ist sofort verfügbar
# Nicht wie in anderen Bibliotheken 

#Ausserdem v_fn.grad_fn ist jetzt belegt mit einem Objekt, das die Operation darstellt, die die Variable im Graphen erzeugt hat

torch.autograd.grad(v_fn,v)#d(v_fn/v)

(tensor([[ 2.,  2.]]),)

In [22]:
#Oder
v1 = Variable(torch.Tensor([1, 2]), requires_grad=True)
v2 = Variable(torch.Tensor([3]), requires_grad=True)
v_fn = torch.sum(v1 * v2)

In [23]:
v_fn.backward()

In [24]:
print(v1.grad)

tensor([ 3.,  3.])


In [25]:
print(v2.grad)

tensor([ 3.])
