# PyTorch

Warum lieber PyTorch?

Tesorflow:
- von Google
- Unglaublich Low-Level --> Fast alles selber schreiben
    - Flexibilität aber vielleicht...
    - Code nicht mehr so gut lesbar :-)
    
- Man nutzt lieber Keras  
    - Nicht von Google
    - Debugging nicht so geil :/
    - Wirklich easy
- Static computation Graph!

PyTorch:
- von Facebook
- High Level (eine Art Keras)
- sehr jung --> Windows Version lange "beta" geblieben
- Viel Umstieg nach PyTorch
- Dynamic computation graph :-)



### Static computation Graphs

Beispiel: Daten -> Convolution -> Fully Connected

Der Graph ist statisch:
- Das Bild ist immer genau dasselbe, z.B. 32x32. 


### Dynamic Computation Graph
- Die Anzahl an Neuronen kann sich zur Laufzeit verändern
    - If und else Verzweigungen sind bsp. möglich
    - Man kann eine Berechnung für die ersten X-Epochen machen, danach sie verändern
Daten -> Convolution:
    - If something:
        - Pooling A
    - Else:
        - Pooling B
-> Fully Connected    
    - Der Input-Layer passt sich quasi den Inputs :-)
    - Wie kann das genau so schnell sein, wenn Änderungen zur Laufzeit möglich sind? Läuft fast genau so schnell wie TensorFlow :)

In [1]:
import torch

## Tensoren

In [4]:
x = torch.randn(5,3) #Matrix 5x3 (5 Zeilen, 3 Spalten)
x

tensor([[-2.2789, -0.2773, -0.0543],
        [-0.3424,  1.5185, -1.3986],
        [-0.6996,  2.1158, -0.3792],
        [ 2.5705,  0.6989, -0.7818],
        [ 1.1512, -0.1644,  0.2251]])

In [6]:
matr3 = torch.randn(5,2,2) #5 2x2 Matrixen
matr3

tensor([[[-2.0781,  1.7730],
         [ 0.1685, -0.5971]],

        [[-1.1920, -0.6030],
         [ 1.1426,  3.2733]],

        [[-0.6611, -0.2770],
         [-0.5768,  1.3310]],

        [[ 0.0602,  2.3778],
         [ 1.8561,  0.3390]],

        [[-0.7297,  0.2842],
         [-0.0853,  0.6249]]])

In [19]:
a = torch.randint(1,10,(2,3))
b = torch.randint(1,10,(2,3))

### Elementenweise Operationen

In [20]:
print("Addition: ", torch.add(a,b), "\noder:", a+b)
print("*"*60)
print("Subtraktion: ", torch.sub(a,b), "\noder:", a-b)
print("*"*60)
print("Multiplikation: ", torch.mul(a,b), "\noder:", a*b)
print("*"*60)
print("Division: ", torch.div(a,b), "\noder:", a/b)

Addition:  tensor([[  9.,   5.,  12.],
        [  7.,   4.,   6.]]) 
oder: tensor([[  9.,   5.,  12.],
        [  7.,   4.,   6.]])
************************************************************
Subtraktion:  tensor([[ 3.,  1., -6.],
        [ 5.,  2.,  0.]]) 
oder: tensor([[ 3.,  1., -6.],
        [ 5.,  2.,  0.]])
************************************************************
Multiplikation:  tensor([[ 18.,   6.,  27.],
        [  6.,   3.,   9.]]) 
oder: tensor([[ 18.,   6.,  27.],
        [  6.,   3.,   9.]])
************************************************************
Division:  tensor([[ 2.0000,  1.5000,  0.3333],
        [ 6.0000,  3.0000,  1.0000]]) 
oder: tensor([[ 2.0000,  1.5000,  0.3333],
        [ 6.0000,  3.0000,  1.0000]])


### Matrizenmultiplikation

### CUDA: Berechnungen auf der Grafikkarte

In [24]:
x = torch.randn((60000,784))
y = torch.randn((60000,784))
#Tensors nach CUDA
if torch.cuda.is_available():
    print("CUDA available")
    x = x.cuda()#
    y = y.cuda()
x+y

CUDA available


tensor([[ 2.0356,  3.0388, -1.1823,  ...,  1.0606,  1.0627, -0.2655],
        [ 1.6800, -0.2064, -0.2593,  ...,  1.9300, -0.8253,  0.1486],
        [-0.8029,  1.2764,  2.2142,  ...,  2.4638,  0.6943,  0.0832],
        ...,
        [ 1.8547, -0.6906, -1.1779,  ..., -1.1348,  3.3192, -0.1652],
        [-2.8268, -1.0857,  3.2563,  ...,  1.2146,  0.5481, -1.6993],
        [ 1.1480, -0.0482, -0.7900,  ..., -1.7810,  0.8314,  0.5277]], device='cuda:0')

## Eigenes Neuronales Netzwerk in PyTorch

In [95]:
import os
import torch
import torch.nn as nn 
import torch.nn.functional as F #FUnktionen
from torch.autograd import Variable #Variablen - kann man backpropagieren
import torch.optim as optim

In [69]:
#Klasse vom Neuronalen Netz erzeugen
class Network(nn.Module):
    def __init__(self):
        #Konstruktor aus Superklasse
        super(Network, self).__init__()
        
        #Layer definieren
        self.lin1 = nn.Linear(10,11)
        self.lin2 = nn.Linear(11,10)
    
    def forward(self, x):
        """ Berechnet bis zum Output """
        x = F.relu(self.lin1(x))
        #Letzter Schritt ohne Aktivierungsfunktion
        x = self.lin2(x)
        return x
    
    def num_flat_features(self, x):
        """ 
        Ausgabe von den Berechnungen aus nn.Module 
        x ist eine Variable fuer einen Tensor, Tensor ist drinnen
        """ 
        print(x.size())
        print(x.size()[1:])
        size = x.size()[1:] #ausser Batch-Dimension
        num = 1
        for i in size:
            num *=i 
        return num    

In [99]:
net = Network()
if torch.cuda.is_available():
    net = net.cuda()
if os.path.isfile("net.pt"):
    print("Bestehendes Netz wird geladen")
    net = torch.load("net.pt")

Bestehendes Netz wird geladen


## Das Netz lernt

1. Criterion für Berechnung des Fehlers
2. Optimizer für das Lernen

Speichern mit `torch.save()`, Laden mit `torch.load()`

In [100]:
label = [0,1,1,0,1,0,0,0,0,0] #
target = Variable(torch.Tensor([label for _ in range(10)])) #10x5 targets
if torch.cuda.is_available():
        target = target.cuda()

In [102]:
for i in range(50):
    # Baut aus einem Tensor eine Variable, Tensoren sind die Inhalte davon
    x = [1,0,0,1,0,1,1,1,1,1] #
    input = Variable(torch.Tensor([x for _ in range(10)])) #10x5 targets
    if torch.cuda.is_available():
        input = input.cuda()
    out = net(input)
    #print(out) #10x5
    
    criterion = nn.MSELoss()
    loss = criterion(out, target)
    if i % 10 == 0:
        print("Fehler: ", loss.item())
    #print("Fehler in der 1.Stufe: ", loss.grad_fn.next_functions[0][0])
    net.zero_grad() #Veraenderung auf null setzen
    loss.backward() #Backpropagation des Loss
    optimizer = optim.SGD(net.parameters(), lr=0.10)
    optimizer.step()

Fehler:  1.3628334910782171e-14
Fehler:  1.3578027929978843e-14
Fehler:  1.23345776341789e-14
Fehler:  1.1979306605112029e-14
Fehler:  1.162542301601276e-14


In [103]:
torch.save(net,"net.pt")

## MNIST mit PyTorch

In [107]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [109]:
from torchvision import datasets, transforms
from torch.autograd import Variable

In [ ]:
### Daten herunterladen und bereitstellen

loader = torch.utils.data.DataLoader(datasets.MNIST)